# Generated by Django 2.0.7 on 2020-05-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=10)),
                ('slug', models.CharField(max_length=50)),
                ('new_confirmed', models.IntegerField()),
                ('total_confirmed', models.IntegerField()),
                ('new_deaths', models.IntegerField()),
                ('total_deaths', models.IntegerField()),
                ('new_recovered', models.IntegerField()),
                ('total_recovered', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('insert_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WorldTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_confirmed', models.IntegerField()),
                ('total_deaths', models.IntegerField()),
                ('total_recovered', models.IntegerField()),
                ('insert_time', models.DateTimeField()),
            ],
        ),
    ]
